################################################################################
# Parameters have to be specified by the caller, to customize the pipeline
# for a certain project
################################################################################
parameters:

  # Identifies each job uniquely when ci-job-template.yml is used in a loop. 
  # Can only contain characters, numbers, and underscores.
  # Also used to extend names of files published in extensions.
- name: id
  type: string
  default: ''
  
  # Enables an easy integration with custom jobs. 
  # The parameter will be passed as is to the 'dependsOn' property of the job.
- name: dependsOn
  type: string
  default: ''

  # Enables an easy integration with custom jobs. 
  # The parameter will be passed as is to the 'condition' property of the job.
- name: condition
  type: string
  default: ''

  # Specifies the name of the agent pool.
  # The pool name can't be hardcoded in the pipeline template.
- name: agentPool
  type: string
  default: ''

  # Name of the Service connection to the Docker repository
- name: dockerRepoICMServiceConnection
  type: string
  default: ''

  # Name of Docker repository, containing the ICM-customization product images.
- name: dockerRepoICM
  type: string
  default: ''

  # Name of projects Maven repository.
- name: artifactsFeed
  type: string
  default: ''

  # Name of the service connection to the ACR of the project.
- name: acrServiceConnection
  type: string
  default: ''

  # Name of the ARM service connection to the ACR of the project.
  # Note: This is not a service connection for Docker.
  # It is a service connection for the Azure Resource Manager (ARM) 
  # with access to the Azure Container Registry (ACR) resource.
- name: acrServiceConnectionArm
  type: string
  default: '$(REPO_SERVICE_CONNECTION_ARM)'

  # URL of the Azure Container Registry (ACR), including the hostname.
  # Example: <NAME_OF_ACR>.azurecr.io
- name: acr
  type: string
  default: ''

  # Specifies the name of the repository. 
- name: projectPath
  type: string
  default: '$(Build.Repository.Name)'

  # Name of the ci-configuration repositoriy resource.
  # When making adjustments, the 'directoriesConf' parameter must also be adjusted.
- name: envPath
  type: string
  default: 'ci-configuration'

  # Setting required system properties of the JVM
  # When making adjustments, the 'envPath' parameter must also be adjusted.
- name: directoriesConf
  type: string
  default: '-DlicenseDir=$(Pipeline.Workspace)/s/ci-configuration/license -DconfigDir=$(Pipeline.Workspace)/s/ci-configuration/environment'

  # Setting required project properties
- name: repositoriesConf
  type: string
  default: '-PrepoUser=PAT -PrepoPassword=$(System.AccessToken)'

  # Value of the GRADLE_USER_HOME variable
- name: gradleUserHome
  type: string
  default: '$(Pipeline.Workspace)/.gradle'
 
  # Prefix of the GebTest containers
- name: containerPrefix
  type: string
  default: '$(Build.Repository.Name)'

  # Maximum job execution time
- name: jobTimeoutInMinutes
  type: number
  default: 300

  # Specifies whether future jobs should run even if this job fails; defaults to 'false'.
- name: jobContinueOnError
  type: boolean
  default: false

  # Specifies whether all gebTest task should run; defaults to 'true'.
- name: runGebTest
  type: boolean
  default: true

  # gradle gebTest tasks
- name: gebTestTasks
  type: string
  default: 'startSolrCloud startMailSrv startAS startWA startWAA rebuildSearchIndex gebTest'

  # gradle build tasks
- name: gradleBuildTask
  type: string
  default: 'startMSSQL dbPrepare test ishUnitTestReport -x=containerClean'

  # Enable immutable images when created for Git tags.
- name: lockImages
  type: boolean
  default: true

  # Name of template to be executed before all major steps of current job.
- name: preHookTemplate
  type: string
  default: ''
  
  # Name of template to be executed after all major steps of current job.
- name: postHookTemplate
  type: string
  default: ''

  # parameters for code analysis plugin configuration with Gradle v3
  # sonarqube
- name: sonarQubeEnabled
  type: boolean
  default: false

- name: sqGradlePluginVersionChoice
  type: string
  default: 'specify'

- name: sonarQubePluginVersion
  type: string
  default: '2.6.1'

  # CheckStyle
- name: checkStyleEnabled
  type: boolean
  default: false

  # PMD
- name: pmdEnabled
  type: boolean
  default: false

  # SpotBugs
- name: spotBugsEnabled
  type: boolean
  default: false

- name: spotBugsPluginVersion
  type: string
  default: '4.7.0'

  # Specifies the JDK version to make available on the path. Use a whole number version, such as 17 or 21.
- name: javaVersion
  type: string
  default: '17'

  # Specifies whether to perform a DockerHub login before the build steps.
- name: dockerhubLogin
  type: boolean
  default: false

  # Name of the DockerHub registry service connection to use for login.
- name: dockerhubServiceConnection
  type: string
  default: '$(DOCKERHUB_PUBLIC_SERVICE_CONNECTION)'

  # Resource name of this template repository.
- name: templateRepository
  type: string
  default: icm-partner-devops

jobs:
- job: CI${{ parameters.id }}
  pool: '${{ parameters.agentPool }}'
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  continueOnError: ${{ parameters.jobContinueOnError }}
  timeoutInMinutes: ${{ parameters.jobTimeoutInMinutes }}
  workspace:
    clean: all
  variables:
    # See: https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#gradle
    - name: GRADLE_USER_HOME
      value: ${{ parameters.gradleUserHome }}

    # General variables
    - name: TEMP_CONFIG_FILE_PATH
      value: $(Pipeline.Workspace)/config${{ parameters.id }}.md
    - name: TEMP_GEB_LOG_DIR # Geb project path where logs should be saved
      value: $(Pipeline.Workspace)/s/${{ parameters.projectPath }}/build/geb

    # Parameters as variables
    - name: TEMP_TEMPLATE_DIRECTORY
      value: $(Pipeline.Workspace)/s/${{ parameters.templateRepository }}
    - name: TEMP_ID
      value: ${{ parameters.id }}
    - name: TEMP_DOCKER_REPO_ICM_SERVICE_CONNECTION
      value: ${{ parameters.dockerRepoICMServiceConnection }}
    - name: TEMP_DOCKER_REPO_ICM
      value: ${{ parameters.dockerRepoICM }}
    - name: TEMP_ACR_SERVICE_CONNECTION
      value: ${{ parameters.acrServiceConnection }}
    - name: TEMP_ACR_SERVICE_CONNECTION_ARM
      value: ${{ parameters.acrServiceConnectionArm }}
    - name: TEMP_ACR
      value: ${{ parameters.acr }}
    - name: TEMP_ARTIFACTS_FEED
      value: ${{ parameters.artifactsFeed }}
    - name: TEMP_AGENT_POOL
      value: ${{ parameters.agentPool }}
    - name: TEMP_CONDITION
      value: ${{ parameters.condition }}
    - name: TEMP_DEPENDS_ON
      value: ${{ parameters.dependsOn }}
    - name: TEMP_PROJECT_PATH
      value: ${{ parameters.projectPath }}
    - name: TEMP_ENV_PATH
      value: ${{ parameters.envPath }}
    - name: TEMP_DIRECTORIES_CONF
      value: ${{ parameters.directoriesConf }}
    - name: TEMP_REPOSITORIES_CONF
      value: ${{ parameters.repositoriesConf }}
    - name: TEMP_GRADLE_USER_HOME
      value: ${{ parameters.gradleUserHome }}
    - name: TEMP_CONTAINER_PREFIX
      value: ${{ parameters.containerPrefix }}
    - name: TEMP_JOB_TIMEOUT_IN_MINUTES
      value: ${{ parameters.jobTimeoutInMinutes }}
    - name: TEMP_RUN_GEB_TEST
      value: ${{ parameters.runGebTest }}
    - name: TEMP_GEB_TEST_TASKS
      value: ${{ parameters.gebTestTasks }}
    - name: TEMP_GRADLE_BUILD_TASK
      value: ${{ parameters.gradleBuildTask }}
    - name: TEMP_LOCK_IMAGES
      value: ${{ parameters.lockImages }}
    - name: TEMP_PRE_HOOK_TEMPLATE
      value: ${{ parameters.preHookTemplate }}
    - name: TEMP_POST_HOOK_TEMPLATE
      value: ${{ parameters.postHookTemplate }}
    - name: TEMP_DOCKERHUB_LOGIN
      value: ${{ parameters.dockerhubLogin }}
    - name: TEMP_DOCKERHUB_SERVICE_CONNECTION
      value: ${{ parameters.dockerhubServiceConnection }}
    - name: TEMP_SONAR_QUBE_ENABLED
      value: ${{ parameters.sonarQubeEnabled }}
    - name: TEMP_SQ_GRADLE_PLUGIN_VERSION_CHOICE
      value: ${{ parameters.sqGradlePluginVersionChoice }}
    - name: TEMP_SONAR_QUBE_PLUGIN_VERSION
      value: ${{ parameters.sonarQubePluginVersion }}
    - name: TEMP_CHECK_STYLE_ENABLED
      value: ${{ parameters.checkStyleEnabled }}
    - name: TEMP_PMD_ENABLED
      value: ${{ parameters.pmdEnabled }}
    - name: TEMP_SPOT_BUGS_ENABLED
      value: ${{ parameters.spotBugsEnabled }}
    - name: TEMP_SPOT_BUGS_PLUGIN_VERSION
      value: ${{ parameters.spotBugsPluginVersion }}
    - name: TEMP_JAVA_VERSION
      value: ${{ parameters.javaVersion }}

  steps:
    # Checkout all repositories
    - checkout: self
      path: s/${{ parameters.projectPath }}
      clean: true
      persistCredentials: true
    - checkout: ${{ parameters.envPath }}
      path: s/${{ parameters.envPath }}
      clean: true
    - checkout: ${{ parameters.templateRepository }}
      clean: true
      persistCredentials: false
      fetchDepth: 1

    - ${{ if not(eq(parameters.preHookTemplate, '')) }}:
      - template: ${{ parameters.preHookTemplate }}

    # Check all parameters
    - task: Bash@3
      displayName: Validate pipeline parameters
      timeoutInMinutes: 2
      inputs:
        filePath: '$(TEMP_TEMPLATE_DIRECTORY)/tasks/validate_parameters.sh'
      env:
        MAPPED_TEMP_REPOSITORIES_CONF: $(TEMP_REPOSITORIES_CONF)

    # This task is necessary for the version calculation.
    # Otherwise the git repo is always in detached head and
    # SNAPSHOTS are not longer separeted by their name.
    - task: Bash@3
      timeoutInMinutes: 5
      displayName: Checkout $(Build.SourceBranchName)
      inputs:
        workingDirectory: ${{ parameters.projectPath }}
        filePath: '$(TEMP_TEMPLATE_DIRECTORY)/tasks/checkout_repository_resolver.sh'
      condition: ne(variables['Build.SourceBranchName'], 'merge')

    - task: Docker@2
      displayName: Docker Login - dockerRepoICMServiceConnection
      timeoutInMinutes: 1
      inputs:
        containerRegistry: ${{ parameters.dockerRepoICMServiceConnection }}
        command: 'login'

    - task: Docker@2
      displayName: Docker Login - acrServiceConnection
      timeoutInMinutes: 1
      inputs:
        containerRegistry: ${{ parameters.acrServiceConnection }}
        command: 'login'

    - ${{ if parameters.dockerhubLogin }}:
      - task: Docker@2
        displayName: Docker Login - dockerhubServiceConnection
        timeoutInMinutes: 1
        inputs:
          containerRegistry: ${{ parameters.dockerhubServiceConnection }}
          command: 'login'
    
    - task: Cache@2
      timeoutInMinutes: 5
      inputs:
        key: 'gradle | "$(Agent.OS)" | **/build.gradle.kts'
        restoreKeys: |
          gradle | "$(Agent.OS)"
          gradle
        path: $(GRADLE_USER_HOME)
      displayName: Gradle build cache

    - task: JavaToolInstaller@0
      timeoutInMinutes: 1
      inputs:
        versionSpec: '${{ parameters.javaVersion }}'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: Gradle@3
      timeoutInMinutes: 10
      displayName: Check version
      continueOnError: true
      inputs:
        cwd: ${{ parameters.projectPath }}
        gradleWrapperFile: ${{ parameters.projectPath }}/gradlew
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '${{ parameters.javaVersion }}'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        tasks: '-version'

    - task: Gradle@3
      displayName: Clean up container (start)
      continueOnError: true
      inputs:
        cwd: ${{ parameters.projectPath }}
        gradleWrapperFile: ${{ parameters.projectPath }}/gradlew
        options: '-s -i --max-workers 6 ${{ parameters.directoriesConf }} ${{ parameters.repositoriesConf }} -PbuildID=$(Build.BuildId)'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '${{ parameters.javaVersion }}'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        tasks: 'clean containerClean'

    - task: Gradle@3
      displayName: Gradle build
      continueOnError: false
      inputs:
        cwd: ${{ parameters.projectPath }}
        gradleWrapperFile: ${{ parameters.projectPath }}/gradlew
        options: '--refresh-dependencies --scan -s --max-workers 6 -PrunOnCI=true ${{ parameters.directoriesConf }} ${{ parameters.repositoriesConf }} -PbuildID=$(Build.BuildId)'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '${{ parameters.javaVersion }}'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        tasks: '${{ parameters.gradleBuildTask }}'
        # Code Analysis
        sonarQubeRunAnalysis: ${{ parameters.sonarQubeEnabled }}
        sqGradlePluginVersionChoice: ${{ parameters.sqGradlePluginVersionChoice }}
        sonarQubeGradlePluginVersion: '${{ parameters.sonarQubePluginVersion }}'
        checkStyleRunAnalysis: ${{ parameters.checkStyleEnabled }}
        pmdRunAnalysis: ${{ parameters.pmdEnabled }}
        spotBugsAnalysis: ${{ parameters.spotBugsEnabled}}
        spotbugsGradlePluginVersion: '${{ parameters.spotBugsPluginVersion }}'

    - task: Gradle@3
      displayName: Gradle geb tests
      condition: and(succeeded(), ${{ eq(parameters.runGebTest, true) }})
      continueOnError: false
      inputs:
        cwd: ${{ parameters.projectPath }}
        gradleWrapperFile: ${{ parameters.projectPath }}/gradlew
        options: '--refresh-dependencies --scan -s --max-workers 6 -PrunOnCI=true ${{ parameters.directoriesConf }} ${{ parameters.repositoriesConf }} -PbuildID=$(Build.BuildId)'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '${{ parameters.javaVersion }}'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        tasks: '${{ parameters.gebTestTasks }}'

    - task: Bash@3
      displayName: Write Docker logs from geb tests
      condition: and(succeededOrFailed(), ${{ eq(parameters.runGebTest, true) }})
      timeoutInMinutes: 5
      inputs:
        workingDirectory: ${{ parameters.projectPath }}
        filePath: '$(TEMP_TEMPLATE_DIRECTORY)/tasks/write_docker_logs.sh'

    # the task contains the publishing of test results
    - task: Gradle@3
      displayName: Gradle publish artifacts
      continueOnError: false
      inputs:
        cwd: ${{ parameters.projectPath }}
        gradleWrapperFile: ${{ parameters.projectPath }}/gradlew
        options: '--refresh-dependencies --scan -s --max-workers 6 -PrunOnCI=true ${{ parameters.directoriesConf }} ${{ parameters.repositoriesConf }} -PbuildID=$(Build.BuildId)'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '${{ parameters.javaVersion }}'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        tasks: 'buildImages dockerPublish -x=check'

    - task: PublishPipelineArtifact@1
      timeoutInMinutes: 5
      displayName: Provide developer files logs for tests
      inputs:
        targetPath: '${{ parameters.projectPath }}/build/ishunitrunner'
        artifactType: 'pipeline'
        artifactName: ishUnitTest_artifacts
      condition: succeededOrFailed()

    #
    # Post steps
    #
    
    # Generate a build information file and push it as a pipeline artifact.
    - task: Bash@3
      displayName: Create Image Version Overview
      timeoutInMinutes: 5
      env:
        DOCKER_IMAGE_DIRECTORY: ${{ parameters.projectPath }}/build/.docker
      inputs:
        filePath: '$(TEMP_TEMPLATE_DIRECTORY)/tasks/create_image_property_file.sh'

    - task: PublishPipelineArtifact@1
      timeoutInMinutes: 5
      displayName: Provide geb test log files
      inputs:
        targetPath: '$(TEMP_GEB_LOG_DIR)'
        artifactType: 'pipeline'
        artifactName: geb_test_log_files${{ parameters.id }}
      condition: and(succeededOrFailed(), ${{ eq(parameters.runGebTest, true) }})

    - task: PublishPipelineArtifact@1
      timeoutInMinutes: 5
      displayName: Provide developer files logs
      inputs:
        targetPath: '${{ parameters.projectPath }}/build/server/logs'
        artifactType: 'pipeline'
        artifactName: build_artifacts${{ parameters.id }}
      condition: succeededOrFailed()

#    - task: PublishPipelineArtifact@1
#      displayName: Provide developer files Geb tests (sub project my_geb_test)
#      inputs:
#        targetPath: '${{ parameters.projectPath }}/my_geb_test/target/reports/tests/gebTest'
#        artifactType: 'pipeline'
#        artifactName: test_geb_artifacts${{ parameters.id }}
#      condition: succeededOrFailed()

    - task: Gradle@3
      timeoutInMinutes: 10
      displayName: Clean up container (finish)
      inputs:
        cwd: ${{ parameters.projectPath }}
        gradleWrapperFile: ${{ parameters.projectPath }}/gradlew
        options: '-s --max-workers 6 ${{ parameters.directoriesConf }} ${{ parameters.repositoriesConf }} -PbuildID=$(Build.BuildId)'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '${{ parameters.javaVersion }}'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        tasks: 'clean containerClean'
      condition: succeededOrFailed()

    # If the parameter lockImages is true and the Build.SourceBranch is a tag, 
    # then the generated Docker images in the ACR will be made non-overwritable and non-deletable.
    - ${{ if parameters.lockImages }}:
      - task: AzureCLI@2
        timeoutInMinutes: 5
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
        displayName: "Set image attributes"
        env:
          TAG: $(tag)
          IMAGE_NAME: $(imageName)
          REGISTRY: $(registry)
        inputs:
          azureSubscription: '${{ parameters.acrServiceConnectionArm }}'
          scriptType: bash
          scriptLocation: scriptPath
          scriptPath: '$(TEMP_TEMPLATE_DIRECTORY)/tasks/set_image_attributes.sh'

    - ${{ if not(eq(parameters.postHookTemplate, '')) }}:
      - template: ${{ parameters.postHookTemplate }}

    # Clean up all Docker resources generated by the build.
    - task: Bash@3
      displayName: Docker Cleanup
      timeoutInMinutes: 10
      condition: always()
      inputs:
        filePath: '$(TEMP_TEMPLATE_DIRECTORY)/tasks/docker_cleanup.sh'

    # Upload build summary file. The summary will appear on an Extensions tab.
    - task: Bash@3
      timeoutInMinutes: 5
      condition: always()
      continueOnError: true
      displayName: "Provide pipeline configuration"
      inputs:
        filePath: '$(TEMP_TEMPLATE_DIRECTORY)/tasks/provide_pipeline_configuration.sh'

    # Adds a build tag based on the SourceBranch type (Pull Request, Tag, or Branch) for better build classification.
    - task: Bash@3
      timeoutInMinutes: 1
      condition: always()
      continueOnError: true
      displayName: "Add pipeline tag based on SourceBranch type"
      inputs:
        filePath: '$(TEMP_TEMPLATE_DIRECTORY)/tasks/provide_pipeline_tagging.sh'
